/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionProductos.h"

bool_t
xdr_nodo_producto (XDR *xdrs, nodo_producto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, MAXCHAR,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->description, MAXCHAR,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->vat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->price))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguiente, sizeof (nodo_producto), (xdrproc_t) xdr_nodo_producto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_usuario (XDR *xdrs, nodo_usuario *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->username, MAXCHAR,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, MAXCHAR,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_factura (XDR *xdrs, nodo_factura *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id_factura))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha, MAXCHAR,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->username, MAXCHAR,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->precio_bruto))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->descuento))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->precio_neto))
		 return FALSE;
	 if (!xdr_nodo_producto (xdrs, &objp->product))
		 return FALSE;
	return TRUE;
}
