/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionProductos.h"
#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <time.h>
#include <stdbool.h>
#include <unistd.h>

void
gestion_producto_1(char *host)
{
	CLIENT *clnt;
	nodo_usuario  *result_1;
	nodo_usuario  saveuser_1_arg;
	bool_t  *result_2;
	nodo_usuario  isvaliduser_1_arg;
	nodo_producto  *result_3;
	int  findproductbyid_1_arg;
	nodo_producto  *result_4;
	char *findallproducts_1_arg;
	bool_t  *result_5;
	int  addproductinvoice_1_arg;
	nodo_factura  *result_6;
	char *finishinvoice_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_producto, gestion_usuario_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

nodo_usuario user;
	int op = 0;
	do{
		 printf("\n\n\t\tMenú de Opciones\n");
		 printf("\t\t----------------\n");
		 printf("\t1. Registrarse \n\t2. Inicia sesión \n\t3. Salir \n \t");
		 scanf("%d", &op);
		switch (op)
		{
		case 1:

			printf("\n\n\t\t  Registro\n");
		 	printf("\t\t-------------\n");
			printf("\tDigite usuario \n\t");
			scanf("%s", user.username);
			printf("\tDigite contrasenia \n\t");
			scanf("%s", user.password);
			result_1 = saveuser_1(&user, clnt);
			if(result_1 != NULL){
				printf("\n\t¡Registro exitoso! %s\n", result_1->username);
				printf("\t\t-------------\n");
			}else{
				printf("\n\tNo se pudo registrar.%s\n", result_1->username);
				printf("\t\t-------------\n");
			}
			break;	
		case 2:
			printf("\n\n\t\t  Inicio sesión\n");
		 	printf("\t\t-----------------\n");
			printf("\tDigite usuario \n\t");
			scanf("%s", user.username);
			printf("\tDigite contrasenia \n\t");
			scanf("%s", user.password);
			result_2 = isvaliduser_1(&user, clnt);
			if(*result_2 == TRUE){
				int opc_sesion = 0;
		 		printf("\n\n\t\tBienvenido, %s\n", user.username);
		 		printf("\t\t----------------\n");
				do{
					printf("\t1. Comprar \n\t2. Salir \n \t");
					scanf("%d", &opc_sesion);
					switch (opc_sesion)
					{
					case 1:
		 				printf("\n\n\t\tProductos\n");
		 				printf("\t\t--------------\n\t");
						/*Consultar productos al servidor*/
						result_3 = findallproducts_1(NULL, clnt);
						int cont = 1;	
						/*Mostrarlos*/	
						while (result_3 != NULL)
						{
							printf("\t%d. %s \n\t", cont, result_3->name);
							result_3 = result_3->siguiente;
							cont++;
						}
						printf("\t%d. Terminar \n\n", cont);
						int opc_compra = 0;
						while(opc_compra != cont){
							printf("\tDigite opción: \n\t");
							scanf("%d", &opc_compra);
							if(opc_compra != cont){
							addproductinvoice_1(&opc_compra, clnt);
							}
						}
						if(opc_compra == cont){
							result_6 = finishinvoice_1(NULL, clnt);
							printf("\n\n\tFactura Generada.\n");
							printf("\t----------------------\n");
							printf("\tFactura N°: [%d] \n", result_6->id_factura);
							printf("\tUsuario: [%s] \n", result_6->username);
							printf("\tFecha facturada: [%s] \n", result_6->fecha);
							/*Mostrar productos*/
							int cont_p = 1;
							while(*result_6->product.name != '\0'){
								printf("\tProducto[%d] :[%s = $%.1f, Iva = %.2f%] \n", cont_p, result_6->product.name, result_6->product.price, result_6->product.vat);
								result_6->product = *result_6->product.siguiente;
								cont_p ++;
							}
							printf("\tTotal bruto: [$%.2f] \n", result_6->precio_bruto);
							printf("\tTotal descuento: [%.1f% = $%.1f] \n", (result_6->descuento)*100, result_6->precio_bruto* result_6->descuento);
							printf("\tTotal neto: [$%.2f] \n", result_6->precio_neto);
							printf("\t----------------------\n");
						}
						break;
					default:
						break;
					}
				}while(opc_sesion != 2);
			}else{
				printf("\n\n\t\tDatos Incorrectos D:, %s\n", user.username);
				break;
			}
			break;
		case 3:
			exit(1);
			break;
		}
	}while(op != 3);


	result_1 = saveuser_1(&saveuser_1_arg, clnt);
	if (result_1 == (nodo_usuario *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = isvaliduser_1(&isvaliduser_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = findproductbyid_1(&findproductbyid_1_arg, clnt);
	if (result_3 == (nodo_producto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = findallproducts_1((void*)&findallproducts_1_arg, clnt);
	if (result_4 == (nodo_producto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = addproductinvoice_1(&addproductinvoice_1_arg, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = finishinvoice_1((void*)&finishinvoice_1_arg, clnt);
	if (result_6 == (nodo_factura *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_producto_1 (host);
exit (0);
}
