/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionUsuarios.h"
#include "lab3.h"

#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <time.h>
#include <stdbool.h>
#include <unistd.h>

char * generar_rfc(nodo_usuario find_user);
nodo_usuario users[30];
int cont_users = 0;

bool_t *
registrarusuariosistema_1_svc(nodo_usuario *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	if(cont_users <= 30){
		printf("Registrando usuario...: %d\n", argp->cedula);
		users[cont_users] = *argp;
		cont_users++;
		result = TRUE;
	    return &result;
	}
	result = FALSE;
	return &result;
}

nodo_usuario *
consultarusuario_1_svc(int *argp, struct svc_req *rqstp)
{
	static nodo_usuario  result;
	printf("Accediendo a Consultar Usuario: %d \n", *argp);

	nodo_usuario find_user;
	int index=-1;
	/*Buscar*/
	for(int i = 0; i<cont_users; i++){
	if(users[i].cedula == *argp){
	find_user = users[i];
	index = i;
	}
	}
	if(find_user.cedula == 0){
	printf("User not found  \n");
	nodo_usuario response_empty = {
		.cedula = 000,
		.first_name = "NULL",
		.second_name = "NULL"
	};
	result = response_empty;
	return &result;
	}else{
	result = find_user;
	return &result;
	}
}

bool_t *
generarrfc_1_svc(int *argp, struct svc_req *rqstp)
{
	printf("Generando RFC para: %d \n", *argp);
	static bool_t  result;
	nodo_usuario find_user;
	int index=-1;
	/*Buscar*/
	for(int i = 0; i<cont_users; i++){
	if(users[i].cedula == *argp){
	  find_user = users[i];
	  index = i;
	 }
	}
	if(find_user.cedula == 0){
        printf("User not found  \n");
        result = FALSE;
        return &result;
	}else{
        char * rfc = generar_rfc(find_user);
        int aux = 0;
        while(*rfc != 0){
            users[index].rfc[aux] = *rfc;
            *rfc++;
            aux ++;
        }
        memset(users[index].rfc +12,'\0',8*sizeof(char));
        printf("New save RFC : [%s] \n", users[index].rfc);
        result = TRUE;
        return &result;
	}
}

char * generar_rfc(nodo_usuario find_user){
    srand (time(NULL)); 
    char vocales[6] = {'A','E','I', 'O', 'U', '0'};
    char * rfc;
    rfc = malloc(14 * sizeof(char));
    bool flag = false;
    //Primer letra del apellido paterno
    rfc[0] = toupper(find_user.first_last_name[0]);
    char vocal_paterno;
    /*Obtener esa vocal*/
    char * ptr = find_user.first_last_name; 
    int cont_ptr = 0;
    while(*ptr != 0 && flag == false){
        char * ptr_vocales = vocales;
        while(*ptr_vocales != '0'){
            if(toupper(*ptr) == *ptr_vocales && cont_ptr > 0){
                vocal_paterno = *ptr;
                flag = true;
                break;
            }
            *ptr_vocales++;
        }
        *ptr++;
        cont_ptr++;
    }   

    /*Asignación del valor*/
    if(vocal_paterno != 0){
        rfc[1] = toupper(vocal_paterno);
    }

    /*Inicial apellido materno*/
    char * second_last_name = find_user.second_last_name;
    char * first_name = find_user.first_name;
    rfc[2] = toupper(second_last_name[0]);
    rfc[3] = toupper(first_name[0]);
    /*2 últimos números del nacimiento*/
    int anio_nacimiento = find_user.anio_nacimiento;
    int cont = 5;
    while(cont >= 4){
        int digito = anio_nacimiento % 10;
        anio_nacimiento = anio_nacimiento / 10;
        rfc[cont] = digito+'0';
        cont--;
    }

    /*Mes de Nacimiento*/
    int mes_nacimiento = find_user.mes_nacimiento;
    cont=7;
    while(cont >= 6){
        int digito = mes_nacimiento % 10;
        mes_nacimiento = mes_nacimiento / 10;
        rfc[cont] = digito+'0';
        cont--;
    }
    /*Día de Nacimiento*/
    int dia_nacimiento = find_user.dia_nacimiento;
    cont=9;
    while(cont >= 8){
        int digito = dia_nacimiento % 10;
        dia_nacimiento = dia_nacimiento / 10;
        rfc[cont] = digito+'0';
        cont--;
    }
    rfc[10] = (rand () % (9-1+1) + 1)+'0';
    rfc[11] = (rand () % (9-1+1) + 1)+'0';
    rfc[12] = (rand () % (9-1+1) + 1)+'0';

    return rfc;
}
