/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionProductos.h"
#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <time.h>
#include <stdbool.h>
#include <unistd.h>

/*Functions*/
void init_products();
nodo_usuario users[30];
nodo_producto products[7];
int cont_users = 0;
const char * username_session;

nodo_usuario *
saveuser_1_svc(nodo_usuario *argp, struct svc_req *rqstp)
{
	printf("Registrando Usuario... \n");
	static nodo_usuario  result;
	users[cont_users] = *argp;
	result = users[cont_users];
	cont_users++;
	return &result;
}

bool_t *
isvaliduser_1_svc(nodo_usuario *argp, struct svc_req *rqstp)
{
	int cont = 0;
	static bool_t  result;
	int a = 0;
	int b = 1;
	for(int i = 0; i<cont_users; i++){	
		int res_username = strcmp(users[i].username, argp->username);
		int pw_user = strcmp(users[i].password, argp->password);
		if(res_username == 0 && pw_user == 0){
			result = TRUE;
			username_session = users[i].username;
			return &result;
		}
	}
	result = FALSE;
	return &result;
}

nodo_producto *
findproductbyid_1_svc(int *argp, struct svc_req *rqstp)
{
	static nodo_producto  result;
	result = products[*argp-1];
	return &result;
}

nodo_producto *
findallproducts_1_svc(void *argp, struct svc_req *rqstp)
{
	static nodo_producto  result;
	printf("Envíando productos... \n");
	init_products();
	result = products[0];
	return &result;
}

int cont_products_invoice = 0;
nodo_producto products_invoice[50];

int cantidad_arroz_invoice;
int cantidad_frijol_invoice;
int cantidad_aceite_invoice;
bool aplica_promocion = false;

bool_t *
addproductinvoice_1_svc(int *argp, struct svc_req *rqstp)
{
	if(cont_products_invoice == 0){
		memset(products_invoice,0,30*sizeof(nodo_producto));
	}
	/*Promoción: Por más de 3 productos de: aceite, frijo o arroz, recibe 2 pastas gratis :D*/
	static bool_t  result;
	nodo_producto * p = findproductbyid_1_svc(argp,NULL);
	switch (p->id)
	{
	case 1:
		cantidad_arroz_invoice ++;
		break;
	case 3:
	cantidad_aceite_invoice ++;
		break;
	case 5:
	cantidad_frijol_invoice ++;
		break;
	default:
		break;
	}
	printf("Producto: [%s : %.2lf]", p->name, p->price);
	products_invoice[cont_products_invoice] = *p;
	cont_products_invoice++;
	if((cantidad_aceite_invoice > 3 || cantidad_arroz_invoice > 3 || cantidad_frijol_invoice > 3) && aplica_promocion == false){
		products_invoice[cont_products_invoice] = products[6];
		cont_products_invoice++;
		products_invoice[cont_products_invoice] = products[6];
		cont_products_invoice++;
		aplica_promocion = true;
	}
	printf("\n");
	return &result;
}

nodo_factura *
finishinvoice_1_svc(void *argp, struct svc_req *rqstp)
{
static nodo_factura  result;	
	printf("Generando factura... \n");
	/*Enlazando productos de la factura*/
	for(int i = 0; i <cont_products_invoice; i++){
		products_invoice[i].siguiente = &products_invoice[i+1];
	}
	/*Fecha actual*/
	time_t t;
	struct tm *tm;
	char fechayhora[100];
	t=time(NULL);
	tm=localtime(&t);
	strftime(fechayhora, 100, "%d/%m/%Y", tm);
	printf("\n");
	nodo_factura invoice;
	invoice.id_factura = rand () % (600-100+1) + 100;
	strcpy(invoice.username, username_session);
	strcpy(invoice.fecha, fechayhora);
	invoice.product = products_invoice[0];
	/*Precio bruto*/
	double precio_bruto;
	double precio_neto;
	double descuento = 0;
	for(int i = 0; i<cont_products_invoice; i++){
		precio_bruto += products_invoice[i].price;
		precio_neto += products_invoice[i].price * (1+products_invoice[i].vat);
	}
	/*No se deben cobrar las pastas de la promoción*/
	if(aplica_promocion == true){
		precio_bruto-=3000;
		precio_neto-=3570;
	}
	invoice.precio_bruto = precio_bruto;
	/*Descuento*/
	if(invoice.precio_bruto<=20000){
		descuento = 0;
	}else if(invoice.precio_bruto>20000 && invoice.precio_bruto<=50000){
		descuento = 0.10;
	}else if(invoice.precio_bruto>50000 && invoice.precio_bruto<=200000){
		descuento = 0.15;
	}else{
		descuento = 0.25;
	}
	invoice.descuento = descuento;
	invoice.precio_neto = precio_neto - (precio_neto*descuento);
	result = invoice;
	/*Restaurando valores*/
	aplica_promocion = false;
	cantidad_aceite_invoice=0;
	cantidad_frijol_invoice=0;
	cantidad_arroz_invoice=0;
	cont_products_invoice = 0;
	return &result;
}

void init_products(){
	nodo_producto p1 = {
		.id = 1,
		.name = "Arroz",
		.description = "Arroz Integral",
		.price = 2500.0,
		.vat = 0.19
	};
	nodo_producto p2 = {
		.id = 2,
		.name = "Azucar",
		.description = "Azucar Morena",
		.price = 2400.0,
		.vat = 0.19
	};

	nodo_producto p3 = {
		.id = 3,
		.name = "Aceite",
		.description = "Aceite de Girasol",
		.price = 9000.0,
		.vat = 0.19
	};
	nodo_producto p4 = {
		.id = 4,
		.name = "Panela",
		.description = "Panela del campo",
		.price = 2500.0,
		.vat = 0.19
	};
	nodo_producto p5 = {
		.id = 5,
		.name = "Fríjol",
		.description = "Fríjol calima",
		.price = 4500.0,
		.vat = 0.19
	};
	nodo_producto p6 = {
		.id = 6,
		.name = "Leche",
		.description = "Leche entera",
		.price = 3000.0,
		.vat = 0.19
	};
	nodo_producto p7 = {
		.id = 7,
		.name = "Pastas",
		.description = "Pastas para hacer sopa",
		.price = 1500.0,
		.vat = 0.19
	};

	products [0] = p1;
	products [1] = p2;
	products [2] = p3;
	products [3] = p4;
	products [4] = p5;
	products [5] = p6;
	products [6] = p7;
	/*Enlaces*/
	products[0].siguiente = &products[1];
	products[1].siguiente = &products[2];
	products[2].siguiente = &products[3];
	products[3].siguiente = &products[4];
	products[4].siguiente = &products[5];
	products[5].siguiente = &products[6];
	

}
