/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONPRODUCTOS_H_RPCGEN
#define _GESTIONPRODUCTOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXCHAR 30
#define MAXTIPO 20

struct nodo_producto {
	int id;
	char name[MAXCHAR];
	char description[MAXCHAR];
	double vat;
	double price;
	struct nodo_producto *siguiente;
};
typedef struct nodo_producto nodo_producto;

struct nodo_usuario {
	char username[MAXCHAR];
	char password[MAXCHAR];
};
typedef struct nodo_usuario nodo_usuario;

struct nodo_factura {
	int id_factura;
	char fecha[MAXCHAR];
	char username[MAXCHAR];
	double precio_bruto;
	double descuento;
	double precio_neto;
	nodo_producto product;
};
typedef struct nodo_factura nodo_factura;

#define gestion_producto 0x20000001
#define gestion_usuario_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define saveUser 1
extern  nodo_usuario * saveuser_1(nodo_usuario *, CLIENT *);
extern  nodo_usuario * saveuser_1_svc(nodo_usuario *, struct svc_req *);
#define isValidUser 2
extern  bool_t * isvaliduser_1(nodo_usuario *, CLIENT *);
extern  bool_t * isvaliduser_1_svc(nodo_usuario *, struct svc_req *);
#define findProductById 3
extern  nodo_producto * findproductbyid_1(int *, CLIENT *);
extern  nodo_producto * findproductbyid_1_svc(int *, struct svc_req *);
#define findAllProducts 4
extern  nodo_producto * findallproducts_1(void *, CLIENT *);
extern  nodo_producto * findallproducts_1_svc(void *, struct svc_req *);
#define addProductInvoice 5
extern  bool_t * addproductinvoice_1(int *, CLIENT *);
extern  bool_t * addproductinvoice_1_svc(int *, struct svc_req *);
#define finishInvoice 6
extern  nodo_factura * finishinvoice_1(void *, CLIENT *);
extern  nodo_factura * finishinvoice_1_svc(void *, struct svc_req *);
extern int gestion_producto_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define saveUser 1
extern  nodo_usuario * saveuser_1();
extern  nodo_usuario * saveuser_1_svc();
#define isValidUser 2
extern  bool_t * isvaliduser_1();
extern  bool_t * isvaliduser_1_svc();
#define findProductById 3
extern  nodo_producto * findproductbyid_1();
extern  nodo_producto * findproductbyid_1_svc();
#define findAllProducts 4
extern  nodo_producto * findallproducts_1();
extern  nodo_producto * findallproducts_1_svc();
#define addProductInvoice 5
extern  bool_t * addproductinvoice_1();
extern  bool_t * addproductinvoice_1_svc();
#define finishInvoice 6
extern  nodo_factura * finishinvoice_1();
extern  nodo_factura * finishinvoice_1_svc();
extern int gestion_producto_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_producto (XDR *, nodo_producto*);
extern  bool_t xdr_nodo_usuario (XDR *, nodo_usuario*);
extern  bool_t xdr_nodo_factura (XDR *, nodo_factura*);

#else /* K&R C */
extern bool_t xdr_nodo_producto ();
extern bool_t xdr_nodo_usuario ();
extern bool_t xdr_nodo_factura ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONPRODUCTOS_H_RPCGEN */
