/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONUSUARIOS_H_RPCGEN
#define _GESTIONUSUARIOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXTIPO 20

struct nodo_usuario {
	char first_name[MAXNOM];
	char second_name[MAXNOM];
	char first_last_name[MAXNOM];
	char second_last_name[MAXNOM];
	int dia_nacimiento;
	int mes_nacimiento;
	int anio_nacimiento;
	int cedula;
	char username[MAXNOM];
	char password[MAXNOM];
	char rfc[MAXNOM];
};
typedef struct nodo_usuario nodo_usuario;

#define gestion_usuario 0x20000001
#define gestion_usuario_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarUsuarioSistema 1
extern  bool_t * registrarusuariosistema_1(nodo_usuario *, CLIENT *);
extern  bool_t * registrarusuariosistema_1_svc(nodo_usuario *, struct svc_req *);
#define consultarUsuario 2
extern  nodo_usuario * consultarusuario_1(int *, CLIENT *);
extern  nodo_usuario * consultarusuario_1_svc(int *, struct svc_req *);
#define generarRfc 3
extern  bool_t * generarrfc_1(int *, CLIENT *);
extern  bool_t * generarrfc_1_svc(int *, struct svc_req *);
extern int gestion_usuario_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarUsuarioSistema 1
extern  bool_t * registrarusuariosistema_1();
extern  bool_t * registrarusuariosistema_1_svc();
#define consultarUsuario 2
extern  nodo_usuario * consultarusuario_1();
extern  nodo_usuario * consultarusuario_1_svc();
#define generarRfc 3
extern  bool_t * generarrfc_1();
extern  bool_t * generarrfc_1_svc();
extern int gestion_usuario_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_usuario (XDR *, nodo_usuario*);

#else /* K&R C */
extern bool_t xdr_nodo_usuario ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONUSUARIOS_H_RPCGEN */
